---
- name: Deploy EC2 instance using terraform
  # hosts: localhost
  # connection: local
  hosts: "{{ _hosts | default('os_windows') }}"
  gather_facts: false
  # collections:
  #   - cloud.terraform

  vars:
    project_dir: '/tmp/deployment'

  tasks:
    # - name: Grab instance info
    #   ansible.builtin.git:
    #    repo: https://github.com/sonstar2/ansible-terraform.git
    #    dest: '{{ project_dir }}'

    - name: debug
      debug: var=ansible_user
      
    - name: debug
      debug:
        msg: "{{ ansible_password }}"

    # - name: Deploy terraform configuration file
    #   ansible.builtin.template:
    #     src: windows_userdata.ps1.j2
    #     dest: '{{ project_dir }}/terraform/windows_userdata.ps1'

    # - name: Deploy with force init
    #   cloud.terraform.terraform:
    #     project_path: '{{ project_dir }}/terraform'
    #     state: present
    #     force_init: true