---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
    # name: registry.redhat.io/ubi9:latest

dependencies:
  python:
    - pywinrm>=0.4.3
  python_interpreter:
    python_path: /usr/bin/python3.11

  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: cloud.terraform
      - name: amazon.aws
      - name: servicenow.itsm
options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  append_base: |
    RUN microdnf install -y git
    RUN curl https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo | tee /etc/yum.repos.d/terraform.repo
    RUN microdnf install -y terraform
