---
- name: Send API request and debug complete response
  hosts: localhost
  gather_facts: false
  vars:
    # gpt_prompt: "Please explain this Windows Event: {{ ansible_eda.event.body.winlog.event_id }} in the form of a Sci-fi Novel "
    gpt_prompt: "Please explain this Windows Event: {{ ansible_eda.event.body }} "
  
  tasks:
    - name: Send POST request using uri module
      ansible.builtin.uri:
        url: "http://98.80.168.118:8000/v1/completions"
        method: POST
        headers:
          accept: "application/json"
          Content-Type: "application/json"
          Authorization: "Bearer {{ granite_api_token | default('ansible123!') }}"
        body:
          prompt: "{{ gpt_prompt | default('What is the capital of the USA?') }}"
          max_tokens: "{{ max_tokens | default('500') }}"
        body_format: json
        return_content: true
        status_code: 200
        timeout: 60
      register: response

    - name: Check if response is JSON and debug output
      ansible.builtin.debug:
        msg: "{{ response.json if response.json is defined else response.content }}"

    - name: Check if response is JSON and retrieve model name
      ansible.builtin.debug:
        msg: "{{ response.json.model | basename if response.json is defined else 'Model not found' }}"

    - name: Check if response is JSON and retrieve text
      ansible.builtin.debug:
        msg: "{{ response.json.choices[0].text if response.json is defined and response.json.choices is defined else 'Text not found' }}"

    - name: Create Enhanced incident Ticket
      servicenow.itsm.incident:
        instance:
          host: "{{ servicenow_hostname }}"
          username: "{{ servicenow_username }}"
          password: "{{ servicenow_password }}"
        state: new
        short_description: "{{ ansible_eda.event.body.event.provider }}"
        description: |-
          Details: {{ ansible_eda.event.body.message | default("") }}
          AI Enhanced Details: {{ response.json.choices[0].text if response.json is defined and response.json.choices is defined else 'Text not found' }}
