---
- name: Events from Windows Logs
  hosts: all
  sources:
    - name: Kafka listener for Windows logs topic
      ansible.eda.kafka:
        host: 52.64.198.227
        topic: winlogbeat
        port: 9092
        verify_mode: CERT_NONE
        group_id: eda
        check_hostname: false
  rules:
    - name: AD Account Change
      condition: event.body.winlog.event_id == "4722"
      action:
        run_job_template:
          organization: "Default"
          name: "Windows AD Events"

    - name: Security Event
      condition: event.body.message is search("The Windows Firewall service")
      action:
        run_job_template:
          organization: "Default"
          name: "Windows Enhanced Ticket"

    # - name: Check defined
    #   condition: event.body.winlog is defined
    #   action:
    #     debug:
