---
- name: Events from Windows Logs
  hosts: all
  sources:
    - name: Kafka listener for Windows logs topic
      ansible.eda.kafka:
        host: 52.64.198.227
        topic: windows_events_from_dc01
        port: 9092
        # verify_mode: "CERT_NONE"
        group_id: ansible-eda-winlogbeat
        # check_hostname: false
  rules:
    - name: Check defined
      condition: event.body is defined
      action:
        debug:
