---
- name: Events from Windows Logs
  hosts: all
  sources:
    - name: Kafka listener for Windows logs topic
      ansible.eda.kafka:
        host: 52.64.198.227
        topic: winlogbeat
        port: 9092
        verify_mode: CERT_NONE
        group_id: eda
        check_hostname: false
  rules:
    - name: Check defined
      condition: event.meta is defined
      action:
        debug:
