---
- name: Demo rules with kafka as source
  hosts: all
  sources:
    - ansible.eda.kafka:
        topic: windows_events_from_dc01
        host: 3.26.42.192
        port: 9092
        verify_mode: "CERT_NONE"
        group_id: eda
        check_hostname: false
  rules:
    - name: Check defined
      condition: event.body.i is defined
      action:
        debug:
